* Environment sensor library

This is a library to help developing Arduino based environment monitors. Unlike for simple weather station projects it is assumed that numerous monitoring stations with varying sensor configurations are deployed, reporting back to a central computer collecting and analyzing data.

For sensor communication this library mostly just wraps existing sensor specific libraries, and adds glue to allow a single firmware to be deployed to multiple stations in different configurations.

Currently supported sensors are:

- BMP085 series barometric pressure sensors, connected via i²c. The current generation sensor is the [[https://www.adafruit.com/product/2651][BMP280]], but any older ones will work as well. Requires the [[https://github.com/adafruit/Adafruit-BMP085-Library][BMP085 library]] in the Arduino library folder.
- [[https://learn.adafruit.com/adafruit-mcp9808-precision-i2c-temperature-sensor-guide/overview][MCP9808 temperature sensors]], connected via i²c. Requires the [[https://github.com/adafruit/Adafruit_MCP9808_Library][MCP9808 library]] in the Arduino library folder.
- [[https://www.adafruit.com/product/385][DHT22 humidity sensors.]] Requires the [[https://github.com/adafruit/DHT-sensor-library][DHT sensor library]] in the Arduino library folder

For more details on the hardware setup check the [[https://github.com/aardsoft/mqtt_sensor#sensors][mqtt_sensor hardware section]]. mqtt_sensor currently is the main user of this library.

For building an outside sensor station a [[https://www.thingiverse.com/thing:3114668][Stevenson screen]] style enclosure is recommended.
